name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  linux:
    strategy:
      matrix:
        jdk: ['8', '11', '16', '17-ea']
    runs-on: ubuntu-latest
    name: "Build (JDK ${{ matrix.jdk }})"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.jdk }}
      - run: ./gradlew build
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
